- hosts: deb1
  become: true
  vars:
   mdadm_arrays: 
    # Define array name
     - name: 'md0'
    # Define disk devices to assign to array
       devices:
         - '/dev/sdb'
         - '/dev/sdc'
         - '/dev/sdd'
         - '/dev/sde'
    # Define filesystem to partition array with
       filesystem: 'ext4'
    # Define the array raid level
    # 0|1|4|5|6|10
       level: '10'
    # Define mountpoint for array device
       mountpoint: '/mnt/md0'
    # Define if array should be present or absent
       state: 'present'
  environment:
    PATH: "/usr/local/sbin:/sbin:/usr/sbin:{{ ansible_env.PATH }}"
  roles:
    - role: ansible-mdadm
  tasks:
