- hosts: deb1
  become: true
  vars:
   mdadm_arrays: 
    # Define array name
     - name: 'md0'
    # Define disk devices to assign to array
       devices:
         - '/dev/sdb'
         - '/dev/sda'
         - '/dev/sdd'
         - '/dev/sdf'
    # Define filesystem to partition array with
    #   filesystem: 'ext4'
    # Define the array raid level
    # 0|1|4|5|6|10
       level: '10'
    # Define mountpoint for array device
    #   mountpoint: '/mnt/md0'
    # Define if array should be present or absent
       state: 'present'
  environment:
    PATH: "/usr/local/sbin:/sbin:/usr/sbin:{{ ansible_env.PATH }}"
  roles:
    - role: ansible-mdadm
  tasks:
    - name: Read device information (always use unit when probing)
      community.general.parted: device=/dev/md0 unit=GiB
      register: md0_info

    - name: Remove all partitions from disk
      community.general.parted:
        device: /dev/md0
        number: '{{ item.num }}'
        state: absent
      loop: '{{ md0_info.partitions }}'

    - name: Create a 5 new partitions
      community.general.parted:
        device: /dev/md0
        label: gpt
        number: "{{ item }}"
        state: present
        part_start: 20%
        part_end: 20%
        part_type: extended
        name: "{{ item }}"
      loop: "{{ [1,2,3,4,5] }}"
