- hosts: deb1
  become: true
  vars:
   mdadm_arrays: 
    # Define array name
     - name: 'md0'
    # Define disk devices to assign to array
       devices:
         - '/dev/sdb'
         - '/dev/sda'
         - '/dev/sdd'
         - '/dev/sdf'
    # Define filesystem to partition array with
    #   filesystem: 'ext4'
    # Define the array raid level
    # 0|1|4|5|6|10
       level: '10'
    # Define mountpoint for array device
    #   mountpoint: '/mnt/md0'
    # Define if array should be present or absent
       state: 'present'
  environment:
    PATH: "/usr/local/sbin:/sbin:/usr/sbin:{{ ansible_env.PATH }}"
  roles:
    - role: ansible-mdadm
  tasks:
    - name: Create a 5 new partitions 100%/5 = 20
      community.general.parted:
        device: /dev/md0
        label: gpt
        number: "{{ (item | int | abs) +1 }}"
        state: present
        part_start: "{{ (item | int | abs) * 20 }}%"
        part_end: "{{ (item | int | abs) * 20 + 20 }}%" 
        unit: "%"
        name: "disk{{ (item | int | abs) +1 }}"
      with_sequence: start=0 count=5
